Feature/issue 6
fn-devteam/investment_platform pull request #17
Opened 2020-09-24 04:17 UTC by eduardocampigoto

2020-09-24 10:55 UTC, FelipeNathan requested changes

2020-09-24 10:55 UTC, FelipeNathan commented on src/main/java/com/investment/manager/repository/InvestmentRepository.java
> +	public Page<InvestmentDTO> pagedSearchByClient(@Param("id") Long id, Pageable pageable);
Page<**Investment**>, tua entidade é Investment e não InvestmentDTO, o DTO é transformado após pegar os dados do banco

2020-09-24 10:55 UTC, FelipeNathan commented on src/main/java/com/investment/manager/repository/InvestmentRepository.java
> +	public Page<InvestmentDTO> pagedSearchByBroker(@Param("id") Long id, Pageable pageable);
Page<**Investment**>, tua entidade é Investment e não InvestmentDTO, o DTO é transformado após pegar os dados do banco

2020-09-24 10:55 UTC, FelipeNathan commented on src/main/java/com/investment/manager/service/InvestmentService.java
> +			return investmentRepository.pagedSearchByBroker(client.getId(), pageRequest);
1. pagedSearchBy**Client**
2. Teu repository deve retornar Investment e não InvestmentDTO, depois de retornar as entidades, aí faz a conversão pra DTO, o Page tem o método "getContent()" que vai pegar o conteúdo da "página", getTotalElements() que é o total da consulta, com isso tu cria um novo PageImpl com os dtos
```
Page<Investment> investments = investmentRepository.pagedSearchByClient(client.getId(), pageRequest);
List<InvestmentDTO> dto = investmentMapper.toDTOs(investments.getContent());
return new PageImpl<>(dto, pageRequest, investments.getTotalElements());
```

2020-09-24 10:55 UTC, FelipeNathan commented on src/main/java/com/investment/manager/service/InvestmentService.java
> +			return investmentRepository.pagedSearchByBroker(broker.getId(), pageRequest);
Teu repository deve retornar Investment e não InvestmentDTO, depois de retornar as entidades, aí faz a conversão pra DTO, o Page tem o método "getContent()" que vai pegar o conteúdo da "página", getTotalElements() que é o total da consulta, com isso tu cria um novo PageImpl com os dtos
```
Page<Investment> investments = investmentRepository.pagedSearchByBroker(broker.getId(), pageRequest);
List<InvestmentDTO> dto = investmentMapper.toDTOs(investments.getContent());
return new PageImpl<>(dto, pageRequest, investments.getTotalElements());
```

2020-09-24 10:55 UTC, FelipeNathan commented on src/main/java/com/investment/manager/service/InvestmentService.java
> +		PageRequest pageRequest = PageRequest.of(page, size, Sort.DEFAULT_DIRECTION.ASC);
PageRequest.of(page, size), se não passar um Sort.DIRECTION, ele ja usa por default o ASC, então nesse caso é desnecessário passar o terceiro parâmetro, aí pode remover até o @SupressWarning("static-access")

2020-09-24 10:55 UTC, FelipeNathan commented on src/main/java/com/investment/manager/service/InvestmentService.java
> +		return new PageImpl<>(investmentMapper.toDTOs(investmentRepository.findAll()), pageRequest, size);
Criou o pageRequest pra não paginar a consulta?
Use da mesma forma que nas queries dos métodos anteriores, o JpaRepository tem um findAll(pageable) que aceita o pageable (page request) e pagina o findAll

No lugar do size, usa o getTotalElements() do objeto Page<Investment> daí

2020-09-24 10:55 UTC, FelipeNathan commented on src/main/java/com/investment/manager/controller/InvestmentController.java
> +			@RequestParam(value = "size", required = false, defaultValue = "10") int size) {
Tipos primitivos (int) não aceitam nulo, caso não receba valor, ja vem com o default, que no caso do int é 0, portanto pra esse tipo não precisa atribuir defaultValue = "0"

2020-09-24 10:55 UTC, FelipeNathan commented on src/main/java/com/investment/manager/repository/UserRepository.java
> +	@Query("FROM User u WHERE LOWER(u.name) LIKE %:searchParam% ")
Não precisa do `Select u` na frente do `From User u`?

2020-09-26 13:07 UTC, FelipeNathan requested changes

2020-09-26 13:07 UTC, FelipeNathan commented on src/main/java/com/investment/manager/repository/BankRepository.java
> +	public Page<Investment> pagedSearchByCode(Pageable pageable, @Param("id") String id);
Se for filtrar somente 1 registro não precisa paginar, pode voltar direto o Investment
Usa paginação só se for listar muitos registros (o findAll por exemplo ou alguma query que traria registros demais, como um `SELECT b FROM Bank WHERE name LIKE "Banco%"` que traria todos os registros que começam com Banco)

2020-09-26 13:07 UTC, FelipeNathan commented on src/main/java/com/investment/manager/repository/BankRepository.java
> +	public Page<Investment> pagedSearchByName(Pageable pageable, @Param("name") String name);
Assim como na dica anterior, se for filtrar pelo nome do banco de fato, não precisa paginar, mas nesse caso, por nome, acho válido fazer com "LIKE", aí pode manter paginado

**Obs**: em ambos os métodos, o Page<> ta com INVESTMENT e não com BANK e a consulta é de Bank (o que faz sentido por ser um repository de banco)

2020-09-26 13:07 UTC, FelipeNathan commented on src/main/java/com/investment/manager/repository/InvestmentRepository.java
> +	public Page<Investment> pagedSearchByBroker(Pageable pageable, @Param("id") Long id);
1. A consulta deveria ser i.broker = :id
2. Mesma dica lá do bank repository, não precisa paginar se trazer só um registro. (em ambas as consultas)
Aí retorna o DTO direto pra página, sem ser Page<DTO>

2020-09-26 13:07 UTC, FelipeNathan commented on src/main/java/com/investment/manager/service/BankService.java
> +    	return new PageImpl<>(bankDtos, pageRequest, banks.getTotalElements());
:clap: :clap: :clap:

2020-09-26 13:07 UTC, FelipeNathan commented on src/main/java/com/investment/manager/service/InvestmentService.java
>  		return new PageImpl<>(investmentMapper.toDTOs(investmentRepository.findAll()), pageRequest, size);
Faltou ajustar esse cara igual aos demais...
o `size` fica no PageRequest, mas no PageImpl vai o page.getTotalElements()

2020-09-28 12:28 UTC, eduardocampigoto commented on src/main/java/com/investment/manager/repository/InvestmentRepository.java
> +	public Page<Investment> pagedSearchByBroker(Pageable pageable, @Param("id") Long id);
Na verdade aqui vai trazer vários registros, um cliente ou broker pode ter vários investimentos.

2020-09-28 12:38 UTC, eduardocampigoto commented on src/main/java/com/investment/manager/controller/InvestmentController.java
> +			@RequestParam(value = "size", required = false, defaultValue = "10") int size) {
Beleza, tirei, não foi nesse commit, mas vai no próximo.

2020-09-28 13:11 UTC, FelipeNathan commented on src/main/java/com/investment/manager/repository/InvestmentRepository.java
> +	public Page<Investment> pagedSearchByBroker(Pageable pageable, @Param("id") Long id);
Ah, boa, não me liguei que era do Investment :+1:  ta certo então (só pra ve se tava ligado)

2020-09-28 18:30 UTC, FelipeNathan requested changes

2020-09-28 18:30 UTC, FelipeNathan commented on src/main/java/com/investment/manager/controller/InvestmentController.java
> +	@GetMapping(value = "/broker/{broker}", produces = MediaType.APPLICATION_JSON_VALUE)
Melhor passar somente o ID do broker, aí utilize /{id} e @PathVariable("id") Long id; (se o tipo for Long)

2020-09-28 18:30 UTC, FelipeNathan commented on src/main/java/com/investment/manager/controller/InvestmentController.java
> +	public Page<InvestmentDTO> getByClient(@RequestParam("id") UserDTO client,
Aqui meio que parece estar esperando só o ID mesmo, mas utilize @PathVariable("id") Long id; (se o tipo for Long)

2020-09-28 18:30 UTC, FelipeNathan commented on src/main/java/com/investment/manager/repository/InvestmentRepository.java
> +	public Page<Investment> pagedSearchByClient(Pageable pageable, @Param("id") Long id);
Valide ambas as queries, que são HQL / JpaQL, cada atributo é acessado como se fosse objeto de classe e não campo do banco ou seja:
`i.client` é o mesmo que `i.getClient()`
então pra validar o id, use
`i.client.id` que seria o mesmo que `i.getClient().getId()`

2020-10-13 18:26 UTC, FelipeNathan requested changes

2020-10-13 18:26 UTC, FelipeNathan commented on src/main/java/com/investment/manager/dto/UserDTO.java
> +
Não deveria ser AccountDTO ?

2020-10-16 12:17 UTC, FelipeNathan approved these changes

2020-10-16 12:17 UTC, merged